### ISSUE TITLE
Add extension watch mode

### ISSUE THREAD

**Issue by blink1073** [blink1073/juptyerlab-module-federation#14]
Need a script that runs a webpack watch on the entry point of a package.
When things change, copy the built files in `share/jupyter/labextensions`

**Comment by blink1073** [comment]
We don't need to copy files, we can add a path for the extension, cf #29.  We will instead run a `watch` version of our entry script for each extension in `develop` mode, so that when the user makes a change, they see it update in the console and then can refresh the browser page to pick up the extension changes, since we are not caching extension files.

**Comment by jasongrout** [comment]
> since we are not caching extension files.

Since we control the file generation (via webpack), we can put a hash in each filename, so perhaps we can enable caching. We can look at this after the API freeze.

**Comment by blink1073** [comment]
We will in fact need to copy files, cf https://github.com/jupyterlab/jupyterlab-module-federation/issues/29#issuecomment-664912297, so we'll need a copy step as part of the watcher (parallel watcher that pushes to the appropriate `share/jupyter/labextensions`).

**Comment by blink1073** [comment]
We need to add config data during `labextension develop` so we can track it for watch mode

**Comment by blink1073** [comment]
Tracked in https://github.com/jupyterlab/jupyterlab/issues/8869
