### ISSUE TITLE
Add a script to create an extension bundle

### ISSUE THREAD

**Issue by blink1073** [blink1073/juptyerlab-module-federation#2]
It should accept a directory with a `package.json` file with `jupyterlab` metadata.

- It should produce an output similar to the current `md_package` directory
- It will be a part of `buildutils` in core and exposed as a `python` entry point script as well
- input is the extension package source
- output is the set of webpack output files in a target directory
- Needs a way to configure extra singleton packages beyond the builtin list, as well as maybe opt out of the singleton packages from the system?

**Comment by blink1073** [comment]
Rules for extension authors:
- Should include imported dependencies in `package.json` - these are automatically shared
- Should include `singletonPackages` as needed to map to [`singleton`](https://github.com/module-federation/module-federation-examples/blob/2f4118ad452ba6cff85d14c8417de5048bbee2e5/advanced-api/automatic-vendor-sharing/app1/webpack.config.js#L52)
- Can add `nonSharedPackages` and `nonSingletonPackages` as overrides to core behavior.

Extension builder rules:
- Start with core `sharedPackages`
- Update with extension package deps
- Remove `nonSharedPackages`
- Start with core `singletonPackages`
- Update with extension package `singletonPackages`
- Remove extension package `nonSingletonPackages`
- Use the `extension` metadata for the entry point(s)

**Comment by choldgraf** [comment]
does this mean that people could, e.g., `pip install myextension` and it'd automatically activate etc in lab?

**Comment by blink1073** [comment]
Yep, refresh the page and presto chango.  Doesn't work if there is a server component though, until we have hot load discovery of those.

**Comment by choldgraf** [comment]
amazing! this would be great
