### ISSUE TITLE
Test with an extension chain

### ISSUE THREAD

**Issue by blink1073** [blink1073/juptyerlab-module-federation#5]
Make sure that we can have one extension depend on something provided by another.  The classic use case is a Jupyter widget that depends on the widget manager, but we can test something similar.

**Comment by blink1073** [comment]
Minimal repro (perhaps):

- Package has two JS files
- Shares itself as `{ requiredVersion: ~data.version }`
- Entry point loads the second JS file

- `remoteEntry.js` should `register()` both files

More basic, I should be able to register myself even if I have one module.
In the shared config, I should be able to give my own top level name, and see it registered in `remoteEntry.js`

**Comment by blink1073** [comment]
cf https://github.com/webpack/webpack/issues/10352#issuecomment-662394255

Worst case is that extensions have to be different npm packages from token providers.

**Comment by blink1073** [comment]
Big hammer workaround: 

- Create a new npm package on the fly 
- Use the metadata and dependencies from the source package
- Have it link to the source package and `share` its index and also bootstrap its extension entry point
- Run the webpack build against this new package

**Comment by blink1073** [comment]
I'm going to set this aside for now and focus on #20

**Comment by jasongrout** [comment]
> Big hammer workaround:

Just came up with this thought too. I also think this would work around the issue. Glad to see you thought of it a few days ago :).

**Comment by jasongrout** [comment]
cf also the repo to reproduce the issue: https://github.com/blink1073/module-federation-share-self

**Comment by blink1073** [comment]
Next steps:

- Import the middle package [token](https://github.com/jupyterlab/jupyterlab-module-federation/blob/master/middle_package/index.js#L10) [here](https://github.com/jupyterlab/jupyterlab-module-federation/blob/master/md_package/index.js) and add a `console.log` of `middleToken` [here](https://github.com/jupyterlab/jupyterlab-module-federation/blob/db396772f1e9f281597dc9128a5263e434dab45c/md_package/index.js#L35)
- Update the logic in [webpack.config.ext.js](https://github.com/jupyterlab/jupyterlab-module-federation/blob/master/webpack.config.ext.js) to:
    - Create a package in the target build directory
    - Add a file path dependency on the source package
    - Use the dependencies and metadata from the source package
    - Create an entry point and bootstrap file
    - Target that entry point for the build
- Build and launch the app and make sure the console log says "hello"
